Fix error message handling
Production build fails:

```
$ npm run build

> prufen-dash@0.0.0 build
> tsc && vite build

src/ErrorPage.tsx:12:13 - error TS18046: 'error' is of type 'unknown'.

12         <i>{error.statusText || error.message}</i>
               ~~~~~

src/ErrorPage.tsx:12:33 - error TS18046: 'error' is of type 'unknown'.

12         <i>{error.statusText || error.message}</i>
                                   ~~~~~

Found 2 errors in the same file, starting at: src/ErrorPage.tsx:12
```

Using this answer: https://stackoverflow.com/a/76126878/391865 with `error.data.message` instead of `error.error?.message` as suggested in comments.